name: 'Qt C++ CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
          
      # Сборка через CMake
      - run: cmake -B build -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build build --parallel
