name: 'Qt C++ CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Установка Qt (выбираем версию)
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'  # или '5.15.2' для Qt5
          modules: qt6-base qt6-base-dev # нужные модули

      # Сборка через CMake
      - run: cmake -B build -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build build --parallel
